version: "3"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - ./storage/schema:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=unicorn_user
      - POSTGRES_PASSWORD=magical_password
      - POSTGRES_DB=example
    restart: always

volumes:
  pgdata: {}
