name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Get dependencies
        run: go mod vendor -v

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v .
