name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Run tests with coverage report output
        run: go test ./... -coverprofile=docs/coverage.out

      - name: Comment
        uses: k1LoW/octocov-action@v0
